## PCA Implementation 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets

In [2]:
dataset=datasets.load_iris()

In [9]:
X=dataset['data']
y=dataset['target']

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=10)

In [12]:
pca=PCA(n_components=3)

In [13]:
X_train=pca.fit_transform(X_train)
X_train

array([[ 1.02581145e+00, -5.35523208e-01, -4.99762986e-01],
       [ 2.98230072e+00,  7.94915739e-01,  4.43632568e-01],
       [-1.06158322e-01, -6.96968687e-01, -3.08912694e-01],
       [ 8.90555787e-01, -1.73845316e-01,  4.10045182e-02],
       [ 1.00407661e+00,  3.10615773e-01, -5.39568609e-03],
       [-2.58331220e+00,  1.13531583e+00, -1.28750118e-01],
       [-2.47415243e+00,  5.29417198e-01, -2.60888659e-03],
       [ 1.06217495e+00, -1.36093436e-01, -5.56562504e-02],
       [-2.23915075e+00,  3.48363409e-01, -2.27565321e-01],
       [ 1.98030243e+00,  4.38888284e-02,  1.71750458e-01],
       [-2.55382068e+00, -2.50667895e-01,  4.40373666e-02],
       [-2.66588781e+00, -3.71675746e-01,  3.29237589e-02],
       [ 6.10482557e-01, -1.21548212e+00,  5.36139145e-01],
       [-8.22909045e-01, -7.77813043e-01, -1.70137940e-02],
       [ 2.38628674e+00,  1.95538003e-01,  3.33689348e-01],
       [-2.72781666e+00,  2.10583162e-01,  1.03705613e-01],
       [ 2.17787306e+00,  3.83919886e-01

In [14]:
X_test=pca.transform(X_test)

In [15]:
pca.components_

array([[ 0.35306256, -0.09234735,  0.85995612,  0.35678321],
       [ 0.67829234,  0.71048051, -0.17869435, -0.05661515],
       [-0.57267763,  0.60890283,  0.07491088,  0.54375182]])

In [16]:
pca.explained_variance_ratio_

array([0.92464145, 0.05445146, 0.01645549])