### Sort, Seraching and Counting functions

In [2]:
import numpy as np

In [3]:
arr=np.array([2,1,7,4,3,5])

In [4]:
arr

array([2, 1, 7, 4, 3, 5])

In [5]:
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

In [6]:
np.searchsorted(arr,6)

6

In [7]:
arr1=np.array([0,32,12,53,64,0,2,0,0])

In [8]:
np.count_nonzero(arr1)

5

In [9]:
np.where(arr1>0)

(array([1, 2, 3, 4, 6]),)

In [10]:
np.extract(arr1>0,arr1)

array([32, 12, 53, 64,  2])

In [11]:
#Numpy- Byte Swapping

In [12]:
arr1

array([ 0, 32, 12, 53, 64,  0,  2,  0,  0])

In [13]:
arr.byteswap()

array([144115188075855872,  72057594037927936, 504403158265495552,
       288230376151711744, 216172782113783808, 360287970189639680])

In [14]:
#Numpy - Copies and Views

In [15]:
arr1

array([ 0, 32, 12, 53, 64,  0,  2,  0,  0])

In [16]:
a=np.copy(arr1)

In [17]:
a

array([ 0, 32, 12, 53, 64,  0,  2,  0,  0])

In [18]:
b=arr1.view()

In [19]:
b

array([ 0, 32, 12, 53, 64,  0,  2,  0,  0])

In [20]:
b[0]=100

In [21]:
b

array([100,  32,  12,  53,  64,   0,   2,   0,   0])

In [22]:
arr1

array([100,  32,  12,  53,  64,   0,   2,   0,   0])

In [23]:
#Numpy - Matrix Library

In [24]:
import numpy.matlib as nm

In [25]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [26]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [27]:
# Numpy - Linear Algebra

In [28]:
arr1

array([100,  32,  12,  53,  64,   0,   2,   0,   0])

In [29]:
arr1=np.random.randint([[1,3],[2,4]])
arr2=np.random.randint([[5,8],[10,11]])

In [30]:
np.dot(arr1,arr2)

array([[ 6, 14],
       [ 9, 21]])

In [31]:
arr1

array([[0, 2],
       [0, 3]])

In [32]:
arr2

array([[1, 3],
       [3, 7]])

In [33]:
arr1@arr2

array([[ 6, 14],
       [ 9, 21]])

In [34]:
arr1

array([[0, 2],
       [0, 3]])

In [35]:
arr2

array([[1, 3],
       [3, 7]])

In [36]:
arr1*arr2

array([[ 0,  6],
       [ 0, 21]])

In [37]:
arr1.dot(arr2)

array([[ 6, 14],
       [ 9, 21]])

In [38]:
for i in np.nditer(arr1):
    if(i>10):
        i=0

In [39]:
arr1

array([[0, 2],
       [0, 3]])

In [40]:
np.unique(arr1)

array([0, 2, 3])

In [41]:
arr=[1,32,2,6]

In [42]:
np.flip(arr)

array([ 6,  2, 32,  1])

In [43]:
np.argsort(arr)

array([0, 2, 3, 1])