In [2]:
import numpy as np

In [2]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [8]:
np.arange(0.4,10.9,0.4)

array([ 0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,
        4.8,  5.2,  5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,
        9.2,  9.6, 10. , 10.4, 10.8])

In [9]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [10]:
np.logspace(1,5,5)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
arr=np.ones((3,3))

In [20]:
arr+4

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [4]:
np.empty((3,3))

array([[4.64125762e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [29]:
arr=np.eye(3)

In [30]:
import pandas as pd

In [31]:
pd.DataFrame(arr)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [32]:
np.random.rand(2,3)

array([[0.33128856, 0.24911094, 0.19746191],
       [0.8590243 , 0.49365307, 0.93133877]])

In [34]:
np.random.randn(2,3)

array([[ 0.08422663,  0.86339008, -0.40801192],
       [ 0.29886251,  0.44738006,  0.16758172]])

In [5]:
arr2=np.random.randint(1,6,(3,3))

In [38]:
arr2

array([[4, 4, 3],
       [5, 2, 1],
       [1, 5, 3]])

In [39]:
arr2.size

9

In [40]:
arr2.shape

(3, 3)

In [45]:
arr.reshape(9,-1)

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.]])

In [49]:
arr.reshape(3,3,1)

array([[[1.],
        [0.],
        [0.]],

       [[0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [1.]]])

In [50]:
arr2=np.random.randint(1,30,(4,4))

In [51]:
arr2

array([[14, 16, 28, 21],
       [15, 29, 13, 24],
       [ 4, 26, 20, 14],
       [ 5, 13,  4,  8]])

In [52]:
arr2>10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True, False, False]])

In [54]:
arr2[arr2>10]

array([14, 16, 28, 21, 15, 29, 13, 24, 26, 20, 14, 13])

In [56]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [57]:
arr1

array([[2, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [58]:
arr2

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [59]:
arr1+arr2

array([[3, 3, 3],
       [2, 3, 4],
       [3, 3, 2]])

In [60]:
arr1*arr2

array([[2, 2, 2],
       [1, 2, 4],
       [2, 2, 1]])

In [61]:
arr1@arr2

array([[ 6, 10,  8],
       [ 4,  7,  5],
       [ 4,  6,  5]])

In [62]:
arr1/0

/tmp/ipykernel_1482/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [63]:
#Broadcasting

In [65]:
arr=np.zeros((3,4))

In [66]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [74]:
a=np.array([1,2,3,4])

In [75]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [88]:
b=np.array([[1,2,3]])

In [89]:
b

array([[1, 2, 3]])

In [90]:
b.T

array([[1],
       [2],
       [3]])

In [91]:
arr+b.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])