In [2]:
import numpy as np

In [3]:
l=[1,2,3,4,5]

In [5]:
arr=np.array(l)

In [9]:
type(arr)

numpy.ndarray

In [31]:
mat1=np.array([[1,2,3],[4,5,6]])

In [32]:
arr.ndim

1

In [33]:
mat=np.matrix(l)

In [37]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [35]:
np.asanyarray(mat1)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr

array([1, 2, 3, 4, 5])

In [39]:
a[0]=100

In [40]:
a

array([100,   2,   3,   4,   5])

In [41]:
arr

array([100,   2,   3,   4,   5])

In [42]:
b=np.copy(arr)

In [43]:
b

array([100,   2,   3,   4,   5])

In [44]:
b[0]=253

In [45]:
b

array([253,   2,   3,   4,   5])

In [46]:
arr

array([100,   2,   3,   4,   5])

In [47]:
np.fromfunction(lambda i,j:i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j:i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [50]:
it=list(i*i for i in range(5))

In [52]:
np.fromiter(it,int)

array([ 0,  1,  4,  9, 16])

In [53]:
np.fromstring('35 38 27',sep=' ')

array([35., 38., 27.])

In [55]:
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
mat1.ndim

2

In [58]:
mat1.size

6

In [59]:
arr.shape

(5,)

In [60]:
mat1.shape

(2, 3)

In [61]:
mat1.dtype

dtype('int64')