In [2]:
import numpy as np

In [3]:
#array manipulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[5, 9, 1, 6],
       [4, 3, 8, 3],
       [2, 2, 3, 2],
       [5, 1, 4, 5]])

In [6]:
arr.reshape(8,2)

array([[5, 9],
       [1, 6],
       [4, 3],
       [8, 3],
       [2, 2],
       [3, 2],
       [5, 1],
       [4, 5]])

In [7]:
arr.T

array([[5, 4, 2, 5],
       [9, 3, 2, 1],
       [1, 8, 3, 4],
       [6, 3, 2, 5]])

In [8]:
arr.flatten()

array([5, 9, 1, 6, 4, 3, 8, 3, 2, 2, 3, 2, 5, 1, 4, 5])

In [9]:
np.expand_dims(arr,axis=0)

array([[[5, 9, 1, 6],
        [4, 3, 8, 3],
        [2, 2, 3, 2],
        [5, 1, 4, 5]]])

In [10]:
arr

array([[5, 9, 1, 6],
       [4, 3, 8, 3],
       [2, 2, 3, 2],
       [5, 1, 4, 5]])

In [11]:
np.expand_dims(arr,axis=1)

array([[[5, 9, 1, 6]],

       [[4, 3, 8, 3]],

       [[2, 2, 3, 2]],

       [[5, 1, 4, 5]]])

In [12]:
data=([[1],[2],[3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
np.repeat(data[0],3)

array([1, 1, 1])

In [16]:
np.roll(data,2) #rotate

array([[2],
       [3],
       [1]])

In [17]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
#Numpy Binary operator

In [19]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [20]:
arr1

array([[1, 5, 7, 7],
       [1, 8, 6, 5],
       [6, 5, 1, 3]])

In [21]:
arr2

array([[4, 1, 5, 6],
       [9, 5, 2, 4],
       [4, 1, 7, 5]])

In [22]:
arr1*arr2

array([[ 4,  5, 35, 42],
       [ 9, 40, 12, 20],
       [24,  5,  7, 15]])

In [23]:
arr1>arr2

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False, False]])

In [24]:
arr1+arr2

array([[ 5,  6, 12, 13],
       [10, 13,  8,  9],
       [10,  6,  8,  8]])

In [25]:
#String operations

In [26]:
arr=np.array(["abc","xyz"])

In [27]:
arr

array(['abc', 'xyz'], dtype='<U3')

In [28]:
np.char.upper(arr)

array(['ABC', 'XYZ'], dtype='<U3')

In [29]:
np.char.capitalize(arr)

array(['Abc', 'Xyz'], dtype='<U3')

In [30]:
#Numpy - Mathematical Functions

In [31]:
arr1

array([[1, 5, 7, 7],
       [1, 8, 6, 5],
       [6, 5, 1, 3]])

In [32]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219,  0.75390225,  0.75390225],
       [ 0.54030231, -0.14550003,  0.96017029,  0.28366219],
       [ 0.96017029,  0.28366219,  0.54030231, -0.9899925 ]])

In [33]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.84509804, 0.84509804],
       [0.        , 0.90308999, 0.77815125, 0.69897   ],
       [0.77815125, 0.69897   , 0.        , 0.47712125]])

In [34]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 1.09663316e+03, 1.09663316e+03],
       [2.71828183e+00, 2.98095799e+03, 4.03428793e+02, 1.48413159e+02],
       [4.03428793e+02, 1.48413159e+02, 2.71828183e+00, 2.00855369e+01]])

In [35]:
np.mean(arr1)

4.583333333333333

In [37]:
arr1

array([[1, 5, 7, 7],
       [1, 8, 6, 5],
       [6, 5, 1, 3]])

In [38]:
np.sum(arr1)

55

In [39]:
np.median(arr1)

5.0

In [41]:
np.std(arr1)

2.396467307424734

In [42]:
np.min(arr1)

1

In [43]:
arr1

array([[1, 5, 7, 7],
       [1, 8, 6, 5],
       [6, 5, 1, 3]])

In [44]:
arr2

array([[4, 1, 5, 6],
       [9, 5, 2, 4],
       [4, 1, 7, 5]])

In [45]:
#Arithmetic Operation

In [46]:
np.subtract(arr1,arr2)

array([[-3,  4,  2,  1],
       [-8,  3,  4,  1],
       [ 2,  4, -6, -2]])

In [47]:
np.mod(arr1,arr2)

array([[1, 0, 2, 1],
       [1, 3, 0, 1],
       [2, 0, 1, 3]])