In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [3]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [6]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [8]:
df['target']=dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df['target'].unique()

array([0, 1, 2])

In [11]:
df_copy=df[df['target']!=2]

In [12]:
len(df_copy)

100

In [13]:
df_copy['target'].unique()

array([0, 1])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X=df_copy.drop('target',axis=1)
y=df_copy['target']

In [16]:
X_train, X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=10)

In [17]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [19]:
from sklearn.linear_model import LogisticRegression,LogisticRegressionCV

In [20]:
classification=LogisticRegression()

In [21]:
classification.fit(X_train,y_train)

LogisticRegression()

In [22]:
y_pred=classification.predict(X_test)

In [23]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0])

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [25]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

1.0
[[11  0]
 [ 0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [26]:
from sklearn.model_selection import KFold

In [27]:
cv=KFold(n_splits=5, shuffle=True)

In [28]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [29]:
from sklearn.model_selection import cross_val_score

In [31]:
scores=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)

In [32]:
np.mean(scores)

1.0

In [33]:
# Lets take complex dataset
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

X,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=2)

In [35]:
X_train, X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=10)

In [36]:
complex_logistic=LogisticRegression()

In [37]:
complex_logistic.fit(X_train,y_train)

LogisticRegression()

In [38]:
y_pred=complex_logistic.predict(X_test)

In [39]:
print(accuracy_score(y_test,y_pred))

0.89


In [45]:
cv=KFold(n_splits=5, shuffle=True)
scores2=cross_val_score(complex_logistic,X_train,y_train,scoring='accuracy',cv=cv)
np.mean(scores2)

0.9075